runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

includes:
  - env.yaml

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: 3000ms
