runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

env_variables:
  PROJECT_ID: "jyane-dev"

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: 3000ms
